# Generated by Django 3.2.23 on 2025-06-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AF', 'A FAZER'), ('EM', 'FAZENDO'), ('FN', 'FINALIZADO')], default='AF', max_length=2)),
            ],
        ),
    ]
